// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: d3CzdkbVigKSoVX8yBjtix
// Component: yOGFjVfD2hzW1K
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Valueprop from "../../Valueprop"; // plasmic-import: TSJ1e_oc--oyLy/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: d3CzdkbVigKSoVX8yBjtix/projectcss
import * as sty from "./PlasmicValuesSection3.module.css"; // plasmic-import: yOGFjVfD2hzW1K/css
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: u21l5WRBGIqJxp/icon

export const PlasmicValuesSection3__VariantProps = new Array();

export const PlasmicValuesSection3__ArgProps = new Array("foreground");

function PlasmicValuesSection3__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"foreground"}
        data-plasmic-override={overrides.foreground}
        hasGap={true}
        className={classNames(defaultcss.all, sty.foreground)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___6SL1N)}
              >
                <div
                  className={classNames(defaultcss.all, sty.freeBox___4Hbd9)}
                >
                  <h2
                    className={classNames(
                      defaultcss.h2,
                      defaultcss.__wab_text,
                      sty.h2___6Zokb
                    )}
                  >
                    {"Proposing values"}
                  </h2>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__aoVi5
                  )}
                >
                  {
                    "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__ygS)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___2D2S0)}
                >
                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop___14Dwj
                    )}
                    flat={"flat"}
                    slot={
                      "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg___1Epuy)}
                        role={"img"}
                      />
                    }
                  >
                    {"Powerful"}
                  </Valueprop>

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__waXkG
                    )}
                    flat={"flat"}
                    slot={"Consequat scelerisque a eros taciti nisl a sodales."}
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__x4LqI)}
                        role={"img"}
                      />
                    }
                  >
                    {"Faster"}
                  </Valueprop>

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__fJsT8
                    )}
                    flat={"flat"}
                    slot={"At ut condimentum amet adipiscing ac diam a."}
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__yQc4)}
                        role={"img"}
                      />
                    }
                  >
                    {"Best and brightest"}
                  </Valueprop>

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__pezz7
                    )}
                    flat={"flat"}
                    slot={
                      "Donec purus nec vestibulum volutpat vivamus vulputate suspendisse."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__wFgX3)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__odeZe
                      )}
                    >
                      {"Dynamic range"}
                    </div>
                  </Valueprop>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___60D8)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__prZhi)}
                >
                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__fQzjl
                    )}
                    flat={"flat"}
                    slot={"Commodo pretium himenaeos nisi potenti ad in ante."}
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__fhLSv)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__jM6BZ
                      )}
                    >
                      {"Portable"}
                    </div>
                  </Valueprop>

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__unTZr
                    )}
                    flat={"flat"}
                    slot={"Magna ullamcorper ut arcu nisi a per facilisis."}
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__vqEmU)}
                        role={"img"}
                      />
                    }
                  >
                    {"Production-ready"}
                  </Valueprop>

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__rNfAk
                    )}
                    flat={"flat"}
                    slot={
                      "Ac lobortis praesent sagittis dictumst fermentum vestibulum nunc."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__iLzOh)}
                        role={"img"}
                      />
                    }
                  >
                    {"Magical"}
                  </Valueprop>

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__pReFl
                    )}
                    flat={"flat"}
                    slot={"A parturient mi suspendisse nisl inceptos nullam a."}
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg___3S9EJ)}
                        role={"img"}
                      />
                    }
                  >
                    {"Accessible"}
                  </Valueprop>
                </p.Stack>
              </p.Stack>
            </React.Fragment>
          ),

          value: args.foreground
        })}
      </p.Stack>
    </section>
  );
}

const PlasmicDescendants = {
  root: ["root", "foreground"],
  foreground: ["foreground"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicValuesSection3__ArgProps,
      internalVariantPropNames: PlasmicValuesSection3__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicValuesSection3__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicValuesSection3";
  } else {
    func.displayName = `PlasmicValuesSection3.${nodeName}`;
  }
  return func;
}

export const PlasmicValuesSection3 = Object.assign(
  // Top-level PlasmicValuesSection3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground: makeNodeComponent("foreground"),
    // Metadata about props expected for PlasmicValuesSection3
    internalVariantProps: PlasmicValuesSection3__VariantProps,
    internalArgProps: PlasmicValuesSection3__ArgProps
  }
);

export default PlasmicValuesSection3;
/* prettier-ignore-end */
