// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: d3CzdkbVigKSoVX8yBjtix
// Component: mvOFeaVZnsJKLT
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Logo from "../../Logo"; // plasmic-import: _3yeSdJM8zCXTE/component
import Button from "../../Button"; // plasmic-import: 0GJhn4Yg6J5JLp/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: hfmUcITyrXi2x7/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: d3CzdkbVigKSoVX8yBjtix/projectcss
import * as sty from "./PlasmicNavigation.module.css"; // plasmic-import: mvOFeaVZnsJKLT/css

export const PlasmicNavigation__VariantProps = new Array(
  "dark",
  "centered",
  "hideCta",
  "lightBg"
);

export const PlasmicNavigation__ArgProps = new Array("children", "slot");

function PlasmicNavigation__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__centered]: hasVariant(variants, "centered", "centered"),
        [sty.root__dark]: hasVariant(variants, "dark", "dark"),
        [sty.root__hideCta]: hasVariant(variants, "hideCta", "hideCta"),
        [sty.root__lightBg]: hasVariant(variants, "lightBg", "lightBg")
      })}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox___0KpKu, {
          [sty.freeBox__centered___0KpKuBTzgd]: hasVariant(
            variants,
            "centered",
            "centered"
          ),

          [sty.freeBox__dark___0KpKuPtwkh]: hasVariant(variants, "dark", "dark")
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <Logo className={classNames("__wab_instance", sty.logo___0Elg3)} />
          ),

          value: args.children
        })}

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.freeBox__lvkrp, {
            [sty.freeBox__centered__lvkrpBTzgd]: hasVariant(
              variants,
              "centered",
              "centered"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <React.Fragment>
                <Button
                  className={classNames("__wab_instance", sty.button__mBje0)}
                  navLink={"navLink"}
                  slot={"Services"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button___72TMz)}
                  navLink={"navLink"}
                  slot={"Features"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__u1C4)}
                  navLink={"navLink"}
                  slot={"Company"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__goQi)}
                  navLink={"navLink"}
                  slot={"Contact"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__t44B)}
                  navLink={"navLink"}
                  slot={"Log in"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__flbRq)}
                  darkGray={"darkGray"}
                  slot={"Sign up"}
                />
              </React.Fragment>
            ),

            value: args.slot
          })}
        </p.Stack>

        {(hasVariant(variants, "centered", "centered") ? true : false) ? (
          <div
            className={classNames(defaultcss.all, sty.freeBox__rwgDm, {
              [sty.freeBox__centered__rwgDmbTzgd]: hasVariant(
                variants,
                "centered",
                "centered"
              )
            })}
          >
            {(hasVariant(variants, "centered", "centered") ? false : true) ? (
              <button
                className={classNames(
                  defaultcss.button,
                  defaultcss.__wab_text,
                  sty.button__vLk37,
                  {
                    [sty.button__centered__vLk37BTzgd]: hasVariant(
                      variants,
                      "centered",
                      "centered"
                    ),

                    [sty.button__dark__vLk37Ptwkh]: hasVariant(
                      variants,
                      "dark",
                      "dark"
                    )
                  }
                )}
              >
                {"Sign up"}
              </button>
            ) : null}

            <Button
              className={classNames("__wab_instance", sty.button__fAu3, {
                [sty.button__dark__fAu3Ptwkh]: hasVariant(
                  variants,
                  "dark",
                  "dark"
                )
              })}
              dark={hasVariant(variants, "dark", "dark") ? "dark" : undefined}
              navLink={"navLink"}
              slot={"Log in"}
            />
          </div>
        ) : null}
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavigation__ArgProps,
      internalVariantPropNames: PlasmicNavigation__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicNavigation__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavigation";
  } else {
    func.displayName = `PlasmicNavigation.${nodeName}`;
  }
  return func;
}

export const PlasmicNavigation = Object.assign(
  // Top-level PlasmicNavigation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicNavigation
    internalVariantProps: PlasmicNavigation__VariantProps,
    internalArgProps: PlasmicNavigation__ArgProps
  }
);

export default PlasmicNavigation;
/* prettier-ignore-end */
